### ISSUE TITLE
Progress Bar element of the UI disappears on large file uploads

### ISSUE THREAD

**Issue by aspahwa** [aws-samples/s3uploader-ui#7]
I tested the uploads with multi-GB files and looks like progress bar (including file name, size, percentage and content type) behaves inconsistently with larger uploads. 
Upto 10 GB, progress bar has consistently shown the status of the upload with percentage, however, when I try larger uploads such as 25 GB / 50 GB / 75 GB, the progress bar behaves inconsistently. In some instances, it shows status to completion, where in some cases, it just disappears from from the web page, showing no status of upload. 
Additionally, even though the progress bar disappears, the multipart upload to S3 still continues in the background. This can be verified from the developer tools in the browser where the PUT calls to S3 continue regardless of progress bar showing or not.

**Comment by koiker** [comment]
Hey @aspahwa, I've tested this scenario in my deployment and it worked. I heard a similar issue from a ProServe consultant and after discussing internally and testing, we found that some dependency version was causing the issue. The consultant tried to find which exactly node.js module was causing the issue but in the end the consultant got my configuration files and his deployment worked correctly.
Please, update your dependency versions and rebuild the solution. Let me know if it worked.
