### ISSUE TITLE
Multipart file uploads can not be completed

### ISSUE THREAD

**Issue by bilgincan** [aws-samples/s3uploader-ui#8]
Hello, this implementation works for the uploads < 5MB very well. However, if I try to upload a file > 5MB, it can't complete the upload procedure.

**Comment by bilgincan** [comment]
I meant 5MB, maybe it depends on my browser or the permissions on my S3 Bucket. I tested with Google Chrome on Ubuntu.

**Comment by koiker** [comment]
Hey @bilgincan, I've run a test again in my Google Chrome on OSX with a 10GB file and it uploaded correctly.
Can you test again and this time, open the Google Chrome Developer tools and look into the messages that show in the console. Check if you see any error messages there when you upload. It seems to be a browser problem.

**Comment by bilgincan** [comment]
Hi @koiker, I get this error when I try to upload larger files (meaning > 5MB) "SuchUpload: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed."

In the development tool I see that, the data is being uploaded in multiparts with PUT request. However at the end, there is POST request to complete the upload. As a result of this POST request, I get the following message with the code 400:

<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>YJ3X48K026B2NSET</RequestId><HostId>YTsbG5rP41jd8z8AMDFlP4FPuI7sTbnEs2w6eeOUz3X/5W1PRh4A43Vt60bgZDdTRV+O5sCp8Sc=</HostId></Error>

Then after that, DELETE request "AbortMultipartUploaded" is sent. And finally, the GET request "ListParts" is made and as a result it returns 404 not found, so the multipart upload cant be completed. This time I hosted app on Mac with M1 and I used the Google Chrome browser.

Furthermore, I have to say, I didnt create a new Amplify project for this code. I'm using an existing Amplify configuration, with the following code:

Amplify.configure({
  Auth: {
    identityPoolId: identityPoolId, //REQUIRED - Amazon Cognito Identity Pool ID
    region: region, // REQUIRED - Amazon Cognito Region
    userPoolId: userPoolId, //OPTIONAL - Amazon Cognito User Pool ID
    userPoolWebClientId: userPoolWebClientId, //OPTIONAL - Amazon Cognito Web Client ID
  },
  Storage: {
    AWSS3: {
      bucket: bucketName, //REQUIRED -  Amazon S3 bucket
      region: region, //OPTIONAL -  Amazon service region
    },
  },
});

**Comment by koiker** [comment]
Thanks for the information @bilgincan , it looks like a problem with Amplify or SDK. Searching I found some other users having similar issues as yours. It's seems to be a CORS issue. Some users solved that adding an Etag configuration seems to fix the issue.
Would you mind test this fix in your solution? 
https://github.com/aws-amplify/amplify-js/issues/61#issuecomment-445436658
